version: '3'
services:
  ocr-pymupdf:
    container_name: ocr-pymupdf
    build: .
    volumes:
      - ./input_pdfs:/app/input_pdfs
      - ./output:/app/output
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
