services:
  ocr-pymupdf:
    container_name: ocr-pymupdf
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input_pdfs:/app/input_pdfs
      - ./output:/app/output
      - ./src:/app/src
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
    stdin_open: true
